apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: dev
type: Opaque
data:
  username: dmlqYXk=       # Base64 encoded "vijay"
  password: dmlqYXlAMTIz   # Base64 encoded "vijay@123"
